### PR TITLE
Add general notes for deployments

### PR DESCRIPTION
**Pull request by sztupy**
For more info see https://github.com/CodeYourFuture/curriculum/pull/515

This is splitting out that PR into multiple parts. This is part 1 - the core description for deployments

See also

* https://github.com/CodeYourFuture/curriculum/pull/555
* https://github.com/CodeYourFuture/curriculum/pull/556
* https://github.com/CodeYourFuture/curriculum/pull/557
* https://github.com/CodeYourFuture/curriculum/pull/558

### CODE REVIEW

**Comment by sztupy** [comment]
Build fails as it requires the subdirectories to be present as well due to links:

* https://github.com/CodeYourFuture/curriculum/pull/555
* https://github.com/CodeYourFuture/curriculum/pull/556
* https://github.com/CodeYourFuture/curriculum/pull/557
* https://github.com/CodeYourFuture/curriculum/pull/558

**Comment by Dedekind561** [comment]
@sztupy Your deploy preview isn't building here - how are you planning on linking to these pages on the /guides page?

**Comment by Dedekind561** [comment]
@sztupy I've fixed the issue - you were using incorrect links to point to the netlify guide. Now it is building properly! 😄

**Review by Dedekind561 — APPROVED** [review]
@sztupy Thanks for setting up this guide - and splitting up the PRs!
Let's get this merged and we can start iterating from there...

**Pull request merged**
