### PR TITLE
replace scrimba with khan academy

### PR DESCRIPTION
**Pull request by SallyMcGrath**
## What does this change?

This is a proposed replacement for Scrimba. 

#### Pros:
you can complete it on a library computer
it is 100% free with no upsells
it has videos as well as interactive coding playgrounds
it covers semantic html, devtools, deployment
it can be done in 2.5 hours and will probably take 6-10
it's not madly wrong

#### Cons
It's old! This is the biggest con - it's 9 years old
The projects look crap
You can't type in the video like Scrimba

Overall, it's the best replacement I've found. I looked at 15 possible courses:

w3schools, codeacademy, web.dev, mdn, html.com, educative, freecodecamp, htmldog, htmlacademy, brainstation, learnhtmlcss, learn-html, skillshop and coursera.

Basically the good ones have mega upsell problems. The bad ones are just long infodumps, or sometimes so wildly wrong it's just unhelpful. Or break off into huge lectures about stuff the learner can't possibly grok yet. Or teach emmet before teaching headings. Just - it's a struggle you guys!

### Org Content?

ITD | Step 3 

If we like this, maybe we pair it with build a personal home page for step 4 and get a code review for step 5. 

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

### CODE REVIEW

**Comment by cjyuan** [comment]
I prefer to stick with Scrimba. At least I knew how it works and most participants can eventually finished the step. (Only uncertainty is whether if it will change the middle of an ITD).

Although the systematic way in which Khan Academy introduces HTML and CSS can help the participants learn better,  I am reluctant to try something new 7 days before the launch of next ITD.

**Comment by Ara225** [comment]
I think this pull request is the right thing to do. We probably won't find perfect - the motives to charge in a company are too high and the non profits rarely have the resources to excel, so good enough is fine by me. 

I agree that this is pretty close to the start and therefore major changes are bad but honestly, if we don't rip the plaster off at some point we'll keep making work arounds etc for Scrimba and it will get more and more embedded until none can contemplate a change. What if they decide to charge even for the bits we need or to change the course substantially? At least with Khan Academy they're likely to stay free because of their goals being more or less aligned with ours.

**Comment by SallyMcGrath** [comment]
What I will do is let you two fight it out. 😉 

I'll merge a version of this step as a backup, with the build turned off. And add also a personal home page step that's the same. Then you have all your options. You have the scrimba and blocks version, and if you decide to swap out now or next time, you can do that v quickly if the steps are all there ready

**Comment by SallyMcGrath** [comment]
oh I don't even need to merge it really -- I can just store it here in this closed PR linked to #956

**Comment by SallyMcGrath** [comment]
@cjyuan if you can approve this I will open the next pr off this version

**Comment by cjyuan** [comment]
Replace Scrimba with Khan Academy? Yes. And how do I approve?

**Comment by SallyMcGrath** [comment]
> @SallyMcGrath, Replace Scrimba with Khan Academy? Yes. And how do I approve?

Do you mean you don't have access/perms to approve or you don't know the process to do so?

**Comment by cjyuan** [comment]
I am unfamiliar with the process.

**Review by cjyuan — APPROVED** [review]
Yes. Replace Scrimba by Khan Academy.

**Pull request merged**
