### PR TITLE
Iterate HTML-CSS Sprint 1 timings from NW6

### LINKED ISSUE #308: HTML-CSS Sprint 1 - DevTools Workshop - Times don't add up
**Describe the bug**
The DevTools Workshop is scheduled for 60 minutes, but the workshop contents require us to be working for at least 100 minutes.

**What is wrong with this content?**
The times on the top right of the boxes are incorrect. We ended up skipping part of the workshop in favour of sticking to the schedule. It would be good to correct this for the next cohort.

**How could this be fixed?**
I suggest: 
...
DevTools Workshop 10:20 - 12:20
Lunch 12:20 - 13:20
Study Groups 13:20 - 15:00
Break 15:00 - 15:15
...

Please ratify if that's a good way to structure the day.

**Link to content**
https://curriculum.codeyourfuture.io/html-css/sprints/1/day-plan/

**Additional context**

**Who else might need to know about this?**

### PR DESCRIPTION
**Pull request by JayMayer**
## What does this change?

Module: HTML-CSS
Week(s): 1

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

Changes timings of the "Transferable skills", "Feedback", and "Pairs for next week" sections of HTML-CSS / Sprint 1 / Day-Plan

Fixes #308 

## Who needs to know about this?

@Dedekind561

### CODE REVIEW

**Comment by varuna-v** [comment]
Yes, you're right, the hours of the morning exercise need updating too. https://github.com/CodeYourFuture/curriculum/issues/308

**Comment by SallyMcGrath** [comment]
@varuna-v I think we need more study group time.

**Comment by 40thieves** [comment]
I've taken this off the tech ed board as we think it's in PD's court at the moment.

**Comment by LaraHuzjan** [comment]
@kfklein15 not sure what the situation is here...I saw there was a problem with timing on the tech side, with PD I think the timings are a bit longer than the content says/requires. For ex 'Feedback' was to be 15 min long but there is a 30-minute slot.
If that were corrected there'd be more time. I hope I understood the issue

**Comment by kfklein15** [comment]
@varuna-v and @JayMayer , any reason why our feedback session for PD in the afternoon was increased to 30 min, please? Maybe because 15 min wasn't enough when you tried doing the exercise in class?

**Comment by JayMayer** [comment]
@kfklein15 my memory is that 30 minutes was the time taken to introduce the task, run through the 15 minute role play, then have a group discussion on what was learned.

I appreciate not all of those activities are documented as part of the workshop, but it’s always nice to have time to reflect on the activity with the trainees, and it often leads to interesting discussions.

**Comment by kfklein15** [comment]
This is super helpful, thank you @JayMayer . We should try as much as possible to document things properly as per how it will be run, so very good input.

@LaraHuzjan , let's take a look at this and see what/how we can change this, please? Please raise a ticket on our board linking to this and explaining what needs to be checked (total time of all activities). I will approve this PR in the meantime.

**Review by kfklein15 — APPROVED** [review]
Approving this, although the day is using more than the 1h for PD. We will review this in the near future in a separate ticket - these changes can be done directly via our PD CMS.

**Comment by kfklein15** [comment]
@JayMayer , is this ready to be merged?

**Comment by kfklein15** [comment]
It's showing conflicts. Can work on them and then merge it, please? :)

**Comment by JayMayer** [comment]
@kfklein15 the branch is now up-to-date

**Comment by LaraHuzjan** [comment]
@kfklein15 have created the ticket

**Pull request merged**
