### PR TITLE
Update index React Module success PD.md

### PR DESCRIPTION
**Pull request by LaraHuzjan**
# WARNING MAJOR STRUCTURAL CHANGE IN PROGRESS 12 JAN 2024

Hello contributor! In between you opening this PR and you merging it, you may find a large conflict appears. This is because this site will be broken down into Hugo modules in the same way CodeYourFuture/curriculum-labs is currently structured. The platform (features) will move into the common-theme module and the content (text) will move into the common-content module. The pages will move into the organisation directory. (org-cyf for CYF and org-mcb for MigraCode) You will need to find the new location of your content and move it there. If you are unsure, please ask in the comment thread of this ticket.

## What does this change?

Module: React
Week(s): Module success PD

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

 Update index React Module success PD.md

### CODE REVIEW

**Comment by kfklein15** [comment]
@LaraHuzjan , I found out Success. They are in the Hotel React for some reason instead of the Module success!
https://deploy-preview-582--cyf-curriculum.netlify.app/react/success/

**Comment by SallyMcGrath** [comment]
Happy to help!

Just to walk through the issue clearly -- please correct any wrong parts:

You've added the module success to `org-cyf/content/react/success/index.md`

And it's showing up on the module success page if you go directly to https://curriculum.codeyourfuture.io/react/success/

But on the website it looks like when one clicks on the module success link on this page https://curriculum.codeyourfuture.io/react/

It goes to https://curriculum.codeyourfuture.io/react/product/success/ ? 

This is unexpected! It's nothing you've done. Looks like a weird bug. If you can validate my statements we can open a bug report.

**Comment by kfklein15** [comment]
Hi @SallyMcGrath , 

You've added the module success to org-cyf/content/react/success/index.md

And it's showing up on the module success page if you go directly to https://curriculum.codeyourfuture.io/react/success/

But on the _preview_ of this PR it is going to the product/success page: https://deploy-preview-582--cyf-curriculum.netlify.app/react/success/

And NOT showing on the react/success page:  https://deploy-preview-582--cyf-curriculum.netlify.app/react/product/success/

**Comment by SallyMcGrath** [comment]
This PR is fine - it's exposing not creating a bug, so I'm merging it and the team has already opened a new bug ticket from the convo.

**Review by SallyMcGrath — APPROVED** [review]

**Comment by LaraHuzjan** [comment]
@SallyMcGrath are we ok to create the rest of the PRs for Module success the same way we did or should we wait for the bug to be fixed first?

**Pull request merged**
