### PR TITLE
Update index Node(servers) S2 PD Day Plan.md

### PR DESCRIPTION
**Pull request by LaraHuzjan**
### Common Content?

Block/s

### Common Theme?

Issue number: #issue-number

### Org Content?

Module | Sprint | Page Type | Block Type

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

 Update index Node(servers) S2 PD Day Plan.md

### CODE REVIEW

**Comment by LaraHuzjan** [comment]
@kfklein15 I've done this PR again as there was only a PD Placeholder. 
Where our placeholder was, there was also a "time" line saying time='90'...I wasn't sure whether I should delete it or not.
Also the form at the end where you write what and where you want the changes is different...so this is for Node(Servers) S2 PD Day Plan

**Review by kfklein15 — APPROVED** [review]
LGTM

**Comment by SallyMcGrath** [comment]
Couple things that may be helpful to know:

1. If your content disappeared, open a ticket. (I can just restore it for you rather than you doing it again.)

2. Fill in the change location in this part of the template:

> Org Content?
> Module | Sprint | Page Type | Block Type

Servers 2 | Day plan | PD

**Comment by LaraHuzjan** [comment]
Thanks @SallyMcGrath

**Pull request merged**
