### PR TITLE
Update index JS3 S4 Prep PD.md

### PR DESCRIPTION
**Pull request by kfklein15**
## What does this change?

Module:JS3
Week(s): 4

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

 update PD content

### CODE REVIEW

**Review by SallyMcGrath — COMMENTED** [review]
There are quite a few typos and grammatical errors in this piece. Could it go back and be spellchecked please?

**Review by SallyMcGrath — CHANGES_REQUESTED** [review]
Spellcheck please!

**Comment by kfklein15** [comment]
> Sponsor

Thanks. I need to find a better app than Grammarly. It misses too many things, or maybe it just doesn't like the CMS.

**Comment by kfklein15** [comment]
Coped all text into Google and re-checked it. Thanks, @SallyMcGrath

**Review by SallyMcGrath — APPROVED** [review]

**Pull request merged**
