### PR TITLE
Update index React S3 PD Day Plan.md

### PR DESCRIPTION
**Pull request by LaraHuzjan**
## What does this change?

Module: React 
Week(s): 3

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

Update index React S3 PD Day Plan

### CODE REVIEW

**Review by kfklein15 — APPROVED** [review]
It's ok, but I can see that we have no information about WIP (and even what it stands-for) on the first page. https://deploy-preview-436--cyf-curriculum.netlify.app/react/sprints/3/day-plan/

Does this content not have anything for WIP? If not, we should probably remove the title?

**Comment by LaraHuzjan** [comment]
> It's ok, but I can see that we have no information about WIP (and even what it stands-for) on the first page. https://deploy-preview-436--cyf-curriculum.netlify.app/react/sprints/3/day-plan/
> 
> Does this content not have anything for WIP? If not, we should probably remove the title? These two changes can be done on the PD CMS.

@wainwmr could you give your input, please :)

**Comment by wainwmr** [comment]
> > It's ok, but I can see that we have no information about WIP (and even what it stands-for) on the first page. https://deploy-preview-436--cyf-curriculum.netlify.app/react/sprints/3/day-plan/
> > Does this content not have anything for WIP? If not, we should probably remove the title? These two changes can be done on the PD CMS.
> 
> @wainwmr could you give your input, please :)

@LaraHuzjan , @kfklein15  At one point we had a WIP exercise in the prep for React/S3, and a second WIP exercise plus a feedback exercise in the session, but then we decided that the session was too full.  So we removed the second WIP exercise ([The Penny Game](https://docs.google.com/document/d/1xiP-TpGGUfkFoMEldT4WDfNXqHX9Du6LnChFxWz6Y0o/edit#heading=h.jaoovd7uyqfm)).  So Karen is right, the session no longer contains anything about WIP and it should be removed from the title.

Is it OK that there's a 'prep' exercise that doesn't get consolidated or discussed or anything in the session??

**Comment by LaraHuzjan** [comment]
@kfklein15 Mark said he'll add a short discussion to the class session about WIP. I'll add it to cms then

**Comment by kfklein15** [comment]
@illicitonion I am stuck with this conflict since I don't use the GitHub desktop. Can you help me, please? Happy to jump on a call so I can learn it :D

**Pull request merged**
