### PR TITLE
Use 🔝 not 📎 for back-to-top link

### LINKED ISSUE #48: Fundamentals Prep: Skip links are confusing
**Describe the bug**

There's a paperclip link that hovers over the content on the right-hand side. It appears to go to an anchor at the top, and make a button in the top-left appear which says "Skip to main".

I'm not sure why it's there or what it's for - the paperclip icon doesn't have an obvious meaning to me, jumping to top can be useful but it's not clear that's what it does and there are browser-native shortcuts to do so, and showing a "Skip to main" button which appears to unconditionally scroll the content by about 50px doesn't seem super useful?

I'm not sure if these are better tailored to different styles of pages with different layouts, but right now on this page the paperclip is a bit distracting and I'm not really sure why it's there...

Screenshot with paperclip:
Screenshot 2023-06-11 at 00 00 48

Screenshot of "Skip to main" button:
Screenshot 2023-06-11 at 00 01 09

Screenshot after clicking "Skip to main" button:
Screenshot 2023-06-11 at 00 01 17

**Link to content**

https://cyf-curriculum.netlify.app/fundamentals/prep/

### PR DESCRIPTION
**Pull request by illicitonion**
Fixes #48

### CODE REVIEW

**Comment by SallyMcGrath** [comment]
I just hate how it looks, that's why I didn't use it.

Can we try some others that work better than the paperclip but don't look so ugly as this?

☝️ ?

**Comment by illicitonion** [comment]
How about ⬆ (except black not the green that it would become by default)?
Screenshot 2023-06-14 at 08 41 47

**Comment by SallyMcGrath** [comment]
What about 🔖 ? Bookmark?

**Comment by SallyMcGrath** [comment]
Also, shall we dump this sketchy style on the day plan? It's a nice idea but it's too busy and blocky trying to integrate all these different content formats?
Screenshot 2023-06-14 at 10 49 15



What about something more like

**Comment by SallyMcGrath** [comment]
And then have it peek out behind the blocks on the long view. Would this address your issues?

Screenshot 2023-06-14 at 13 44 22
Screenshot 2023-06-14 at 13 44 11

**Comment by 40thieves** [comment]
Bookmark is good for the metaphor of "go to the links", but I think perhaps we're getting hung up on the metaphor of it being just an "go to top" action. I did think that 🚡 might work for the latter?

But given that https://github.com/CodeYourFuture/curriculum/pull/110 has been merged, I'd say we just see how folks react to that and change it if needed.

Alternatively we just give up on forcing an emoji to fit and just find an icon that we like on [the Noun Project](https://thenounproject.com/search/icons/?iconspage=1&q=up%20arrow).

**Comment by illicitonion** [comment]
Happy to close for now, we can see how things go

**Comment by SallyMcGrath** [comment]
Hee I like helicopter -- I just could not get along with that misaligned dark line. Let's try this and if we get complaints, try helicopter? (I do want to go with the emoji concept as much as pos to connect it to our Slack life)

**Comment by 40thieves** [comment]
(Fwiw it's a cable car 🙂) 

🚁 might actually work though!

**Pull request closed without merging**
