### PR TITLE
Update index updating Module Success Launch.md

### PR DESCRIPTION
**Pull request by kfklein15**
# WARNING MAJOR STRUCTURAL CHANGE IN PROGRESS 12 JAN 2024

Hello contributor! In between you opening this PR and you merging it, you may find a large conflict appears. This is because this site will be broken down into Hugo modules in the same way CodeYourFuture/curriculum-labs is currently structured. The platform (features) will move into the common-theme module and the content (text) will move into the common-content module. The pages will move into the organisation directory. (org-cyf for CYF and org-mcb for MigraCode) You will need to find the new location of your content and move it there. If you are unsure, please ask in the comment thread of this ticket.

## What does this change?

Module: Launch
Week(s): Module success

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

### CODE REVIEW

**Comment by SallyMcGrath** [comment]
Mitch has merged something slightly wrong and there are now errors across the codebase. @Dedekind561 is working on it. I'm sure he'll resolve everything soon. #631

**Comment by kfklein15** [comment]
@Dedekind561 , I saw you merged your other ticket already, but I still cannot make mine pass the tests. Can you help me by any chance?

**Comment by SallyMcGrath** [comment]
Hi - 

This doesn't look like a learning objective to me. It isn't structured in the way we agreed. I've suggested a rephrase

**Comment by kfklein15** [comment]
This was written based on feedback we received from you that it shouldn't be linked to the exit criteria. This way, we can avoid repeating information and not having it up-to-date with the document.
I'd be happy to rewrite it if you explain what is missing on it.

**Comment by SallyMcGrath** [comment]
> This was written based on feedback we received from you that it shouldn't be linked to the exit criteria. This way, we can avoid repeating information and not having it up-to-date with the document. I'd be happy to rewrite it if you explain what is missing on it.

Here's our worksheet on writing learning objectives.

https://docs.google.com/document/d/1NjeGQHCUFTplbj4tCA_lb-I9nugKRVh7PhcFwKXd-uo/edit?usp=sharing

As you can see, if we evaluate this objective from right to left, it does not start with an active verb. 

Secondly, this metadata line probably won't accept markdown.

**Comment by kfklein15** [comment]
Content updated.
Tests still failing.

**Review by SallyMcGrath — APPROVED** [review]
ta!

I'll fix the rest

**Pull request merged**
