### PR TITLE
Revert "Content: Cloud module translation "

### PR DESCRIPTION
**Pull request by Dedekind561**
I hastily merged this PR - which I believe is causing the issue (like the changes to the github template). The diff shows that this PR was modifying a load of files outside the new cloud module. I'm not sure why this was happening though as there are merge commits in the commit log - so I assumed the `cloud-track` branch would be up to date.

## Plan of action to fix merge botch 🤦🏼 :octocat: 
- Merge https://github.com/CodeYourFuture/curriculum/pull/631 - to fix deploy previews (minor errors from links in the deployment guide and files in wrong place)
- Let's merge this PR to revert the changes from the cloud translation
- Re-merge the cloud module translation again in another PR.

### CODE REVIEW

**Review by SallyMcGrath — APPROVED** [review]
Oh is the old template from here and the other stuff from overview?

**Comment by Dedekind561** [comment]
The cloud translation PR was changing the github template and a bunch of files in the `org-cyf` dir too.

**Comment by Dedekind561** [comment]
> Oh is the old template from here and the other stuff from overview?

The overstuff from the overview is dealt with in #631

**Comment by SallyMcGrath** [comment]
Yeah I updated from main a few times but it was waiting around so so long that I guess it was still very outdated

**Pull request merged**
