### PR TITLE
Update index JS1 S4 PD Prep.md

### PR DESCRIPTION
**Pull request by kfklein15**
## What does this change?

Module: JS1
Week(s): 4

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

adding pd prep

### CODE REVIEW

**Review by illicitonion — APPROVED** [review]
One thing I'd consider adding to this (though maybe it'd be over-complicating) is talking about the differences between answering questions to unblock people vs answering questions to help them learn.

One issue we frequently have with our trainees is that when they're stuck with something, they ask a question, and someone else just tells them the answer. The "Explain what you did" section from Julia Evans' page touches on this a little, but we may want to explicitly call it out in our context.

**Comment by kfklein15** [comment]
@illicitonion , I added content in the end ([see this link](https://cyf-pd.netlify.app/blocks/prep-asking-good-questions/readme/)), but I am now thinking this might be better as a coursework than prep for class. What do you think?

**Comment by illicitonion** [comment]
> @illicitonion , I added content in the end ([see this link](https://cyf-pd.netlify.app/blocks/prep-asking-good-questions/readme/)), but I am now thinking this might be better as a coursework than prep for class. What do you think?

Looks great, thanks! Yeah, maybe we can devise an exercise to practice?

**Comment by kfklein15** [comment]
Any suggestion? The lessons is already too full (we only have 1h), and I might have 20 min left in coursework.

**Pull request merged**
