### PR TITLE
857 Data Groups / Sprint 1 - Referenced Medium article is member-only

### LINKED ISSUE #857: Data Groups / Sprint 1 - Referenced Medium article is member-only
The failing fast Medium article referenced here: https://cyf-programming.netlify.app/data-groups/sprints/1/prep/#failing-fast - is now member-only and requires you to have an upgraded Medium account.
We should probably find a freely available alternative.

### PR DESCRIPTION
**Pull request by SallyMcGrath**
Fixes #857

 live debug on this PR to store context for if/when this happens again.

So it's [updated on the repo ](https://github.com/CodeYourFuture/CYF-PD/commit/7be086ff6886385c3590bea5a007e53f0335fafd#diff-241d2808053e07d4a3cb5fb4c356c6c1030a7f3e5d36fd8d1581cd89a5c69db3R23) but not on our mount of the repo. (CYF-PD is a hugo module)

Therefore I posit that the modules are being cached somewhere. ...

Clearing caches on netlify does nothing

Running on local -- same old cached link as on netlify. Is therefore this mount pegged to a specific version of CYF-PD?

I look in org-cyf-itp/go.mod - it has a version but it's not clear that this is pinned.

I run `hugo mod get -u` to see if the versions changes

It does change

I run local again and check the link -- it's updated

So I will fix this by running an update and committing that updated go.mod for now, but maybe there's some better approach because this fails the "consistency check". @illicitonion can you advise?

### CODE REVIEW

**Comment by illicitonion** [comment]
> So I will fix this by running an update and committing that updated go.mod for now, but maybe there's some better approach because this fails the "consistency check". @illicitonion can you advise?

The failing CI job gave a suggestion of what to do; specifically:

```
⚠️  File at path /home/runner/work/curriculum/curriculum/org-cyf-itp/go.mod didn't have some local overrides - its contents should be:
module github.com/CodeYourFuture/curriculum/org-cyf-itp

go 1.22.6

require (
	github.com/CodeYourFuture/CYF-PD v1.0.1-0.2024090[5](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:6)150045-7be086ff6886 // indirect
	github.com/CodeYourFuture/curriculum/common-content v0.0.0-20241022142[7](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:8)07-ee3974f1[8](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:9)eb2 // indirect
	github.com/CodeYourFuture/curriculum/common-theme v0.0.0-20241022142707-ee3[9](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:10)74f18eb2 // indirect
	github.com/CodeYourFuture/curriculum/org-cyf-guides v0.0.0-2024[10](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:11)22142707-ee3974f18eb2 // indirect
	github.com/CodeYourFuture/curriculum/org-cyf-how-this-works v0.0.0-20241022142707-ee3974f18eb2 // indirect
	github.com/CodeYourFuture/curriculum/org-cyf-piscine v0.0.0-20241022142707-ee3974f18eb2 // indirect
	github.com/CodeYourFuture/curriculum/org-cyf-theme v0.0.0-20241022142707-ee3974f18eb2 // indirect
)

replace github.com/CodeYourFuture/curriculum/common-content => ../common-content

replace github.com/CodeYourFuture/curriculum/common-theme => ../common-theme

replace github.com/CodeYourFuture/curriculum/org-cyf-guides => ../org-cyf-guides

replace github.com/CodeYourFuture/curriculum/org-cyf-how-this-works => ../org-cyf-how-this-works

replace github.com/CodeYourFuture/curriculum/org-cyf-piscine => ../org-cyf-piscine

replace github.com/CodeYourFuture/curriculum/org-cyf-theme => ../org-cyf-theme
```

If you replace `org-cyf-itp/go.mod` with the above, things should work.

It looks like your `hugo mod get -u` added a dependency on `github.com/CodeYourFuture/curriculum/org-cyf-theme` which wasn't there before, so we need to add an override for it.

How could the tooling have reported this better to make it more clear?

**Comment by illicitonion** [comment]
Also, do we want CI (maybe in a nightly job?) to automatically run `hugo mod get -u` and either fail a build if there were changes, or create a PR with the changes or something? Otherwise I don't think we're going to pick up new edits to out-of-tree modules like CYF-PD?

**Comment by SallyMcGrath** [comment]
> > So I will fix this by running an update and committing that updated go.mod for now, but maybe there's some better approach because this fails the "consistency check". @illicitonion can you advise?
> 
> The failing CI job gave a suggestion of what to do; specifically:
> 
> ```
> ⚠️  File at path /home/runner/work/curriculum/curriculum/org-cyf-itp/go.mod didn't have some local overrides - its contents should be:
> module github.com/CodeYourFuture/curriculum/org-cyf-itp
> 
> go 1.22.6
> 
> require (
> 	github.com/CodeYourFuture/CYF-PD v1.0.1-0.2024090[5](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:6)150045-7be086ff6886 // indirect
> 	github.com/CodeYourFuture/curriculum/common-content v0.0.0-20241022142[7](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:8)07-ee3974f1[8](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:9)eb2 // indirect
> 	github.com/CodeYourFuture/curriculum/common-theme v0.0.0-20241022142707-ee3[9](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:10)74f18eb2 // indirect
> 	github.com/CodeYourFuture/curriculum/org-cyf-guides v0.0.0-2024[10](https://github.com/CodeYourFuture/curriculum/actions/runs/11495787283/job/31996069422?pr=1116#step:5:11)22142707-ee3974f18eb2 // indirect
> 	github.com/CodeYourFuture/curriculum/org-cyf-how-this-works v0.0.0-20241022142707-ee3974f18eb2 // indirect
> 	github.com/CodeYourFuture/curriculum/org-cyf-piscine v0.0.0-20241022142707-ee3974f18eb2 // indirect
> 	github.com/CodeYourFuture/curriculum/org-cyf-theme v0.0.0-20241022142707-ee3974f18eb2 // indirect
> )
> 
> replace github.com/CodeYourFuture/curriculum/common-content => ../common-content
> 
> replace github.com/CodeYourFuture/curriculum/common-theme => ../common-theme
> 
> replace github.com/CodeYourFuture/curriculum/org-cyf-guides => ../org-cyf-guides
> 
> replace github.com/CodeYourFuture/curriculum/org-cyf-how-this-works => ../org-cyf-how-this-works
> 
> replace github.com/CodeYourFuture/curriculum/org-cyf-piscine => ../org-cyf-piscine
> 
> replace github.com/CodeYourFuture/curriculum/org-cyf-theme => ../org-cyf-theme
> ```
> 
> If you replace `org-cyf-itp/go.mod` with the above, things should work.
> 
> It looks like your `hugo mod get -u` added a dependency on `github.com/CodeYourFuture/curriculum/org-cyf-theme` which wasn't there before, so we need to add an override for it.
> 
> How could the tooling have reported this better to make it more clear?

Oh, when I read this I thought it was telling me that I couldn't update the version in this go.mod and pass this check. That I would have to revert my changes to stay consistent, to this required set. What is it telling me?

**Comment by illicitonion** [comment]
I just pushed an update to the wording of the tooling - how does the output of https://github.com/CodeYourFuture/curriculum/actions/runs/11499627400/job/32008009387?pr=1116 look?

**Review by SallyMcGrath — COMMENTED** [review]
I think you need to approve this @illicitonion

**Review by illicitonion — APPROVED** [review]

**Pull request merged**
