### PR TITLE
Feature: solo view for prep

### PR DESCRIPTION
**Pull request by SallyMcGrath**
## What does this change?

Module: all
Week(s): all 

PREP VIEW ONLY

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

## Description

Sketch of solo view for prep, turning the blocks into a paging/ carousel of content with swipe as well as buttons and table of contents navigation

You can also link directly to a view using fragment identifiers, which should be handy. Basically :

this component sits in the prep.html layout and calls solo-view.js
It accepts content in three slots: header, blocks, and nav. I used slots like this because this way we get to bring our layout with us.
It runs over the content in the slots and caches them in a state object. The constructor basically is a state object, but I thought it was nice to echo the JS3 project for curious trainees.
Then it adds some listeners to navigate through the content. The source of truth for navigation is the generated table of contents. 
We don't prevent default on the TOC links-- we use the hash navigation so that we manage focus for screenreaders and we also make it possible to link to any "slide" directly and have it load in without further navigation
I added swipes for phone/touch, these also just trigger the DOM hash navigation
There's no configuration available. It makes a slide for each block on the page. If there's any .Content on the page that becomes the first block in the list.  It will just do it automatically on every view.
Arguably we want to turn this off sometimes. A toggle for this would be good.

Super basic! Please dig in with your upgrades

Addresses #237

### CODE REVIEW

**Comment by SallyMcGrath** [comment]
PS, I wrote this a bit in the style of our JS3 project, because I thought that might be nice.

**Comment by illicitonion** [comment]
This looks great, thanks for putting it together!!

Misc feedback from playing around with the UI:
* Can we visually disable the "Back" and "Next" buttons on the first/last blocks?
* Do we want to remove the `#toc` bookmark links? I'm not sure they're useful in a single-piece-of-content view...
* Where did the JS3S2 prep go? https://deploy-preview-438--cyf-curriculum.netlify.app/js3/sprints/2/prep/
* Short blocks have a fair bit of scroll before you get to the buttons - could we trim that padding? (See screenshots below)

Screenshot 2023-12-13 at 09 52 56
Screenshot 2023-12-13 at 09 53 08

**Comment by SallyMcGrath** [comment]
> This looks great, thanks for putting it together!!
> 
> Misc feedback from playing around with the UI:
> 
> * Can we visually disable the "Back" and "Next" buttons on the first/last blocks? ✅ 
> * Do we want to remove the `#toc` bookmark links? I'm not sure they're useful in a single-piece-of-content view... ❌ I left it as a return to start and I think that's right. I want the continuity. 
> * Where did the JS3S2 prep go? https://deploy-preview-438--cyf-curriculum.netlify.app/js3/sprints/2/prep/ Just an older branch!
> * Short blocks have a fair bit of scroll before you get to the buttons - could we trim that padding? (See screenshots below) ✅ 


Other changes

◀️ ▶️ Added kbd nav with arrows
🚀 Refactored event listeners to improve performance

**Review by illicitonion — APPROVED** [review]
Perfect, thanks!!

**Pull request merged**
