### PR TITLE
Replace blocks with personal home page step

### PR DESCRIPTION
**Pull request by SallyMcGrath**
## What does this change?

- replace cyf blocks with personal home page step
- tweak step 0 to be a bit less police state
- add links to dashboard throughout

### Org Content?

ITD | Steps | 0-6

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [x] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x] I have run my code to check it works
- [x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

### CODE REVIEW

**Comment by SallyMcGrath** [comment]
@cjyuan here's the content starter for php - edit away

**Comment by SallyMcGrath** [comment]
Oh actually I'll merge and then open a new PR with the changes as that is what we agreed last night!!

**Comment by cjyuan** [comment]
To my understanding, these are the actions I need to take: 
1. Approve this PR to acknowledge that I need to create a separate PR for the changes I am going to make in step 5.
1. Crate a new PR in the following manner: fork https://github.com/CodeYourFuture/curriculum/tree/main, make changes, and then submit a PR after I finished making changes.

Is that correct?

**Review by cjyuan — APPROVED** [review]
As requested

**Pull request merged**
